models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property string $id
 * @property string $username
 * @property string $password
 * @property string $auth_key
 * @property string $password_reset_token
 * @property string $role
 * @property string $fname
 * @property string $lname
 * @property string $phone
 * @property string $address
 * @property string $state
 * @property string $create_at
 */
class Users extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    const SCENARIO_USER_UPDATE = 'user_update';
    const SCENARIO_CREATE_ANY_USER = 'create_any_user';
    const SCENARIO_API_REG = 'api_reg';
    const SCENARIO_API_UPDATE = 'api_update';
   /* 
    const SCENARIO_CREATE_CLIENT = 'create_client';
    
    */

    public $confirm_password;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        
        $scenarios[self::SCENARIO_USER_UPDATE] = [ 'user_pass', 'confirm_password', 'user_nick', 'user_state', 'user_capacity', 'user_create'];
        $scenarios[self::SCENARIO_CREATE_ANY_USER] = ['user_login', 'user_pass', 'confirm_password','user_nick', 'user_role', 'user_state', 'user_capacity', 'user_create'];
      
        return $scenarios;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_login', 'user_pass'], 'required', 'except' => self::SCENARIO_USER_UPDATE],
            [['user_role', 'user_state'], 'string'],
            [['user_capacity'], 'integer'],
            [['user_create'], 'safe'],
            [['user_login', 'user_pass', 'password_reset_token', 'user_nick'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            
            [['user_login'], 'unique', 'message' => '{attribute} {value} is already used in system'],         
            [['auth_key'], 'required', 'on' => 'update_auth_key'],
            ['confirm_password', 'compare', 'compareAttribute' => 'user_pass'],
            [['confirm_password'], 'required', 'on' => [self::SCENARIO_CREATE_ANY_USER]],
            ['user_login', 'email', 'on' => self::SCENARIO_CREATE_ANY_USER, 'message' => 'Login should be email'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {        
        return [
            'user_id' => 'ID',
            'user_login' => 'Login',
            'user_pass' => 'Password',
            'auth_key' => 'Auth Key',
            'password_reset_token' => 'Password Reset Token',
            'user_nick' => 'Nickname',
            'user_role' => 'Role',         
            'user_state' => 'State',
            'user_create' => 'Date created',
            'confirm_password' => 'Confirm password'
        ];
    }

    public function getGroups()
    {
        return $this->hasMany(Groups::className(), ['group_id' => 'group_id'])
            ->viaTable('groupsusers', ['user_id' => 'user_id']);
    }

    public function getRules()
    {
         return $this->hasMany(Rules::className(), ['rule_id' => 'rule_id']) //->where('rulesgroupsusers.user_id <> "0"')
            ->viaTable('rulesgroupsusers', ['user_id' => 'user_id']);
    }


    /** INCLUDE USER LOGIN VALIDATION FUNCTIONS**/
        /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
 
    /**
     * Finds user by user_login
     *
     * @param  string      $user_login
     * @return static|null
     */
    public static function findByUsername($user_login)
    {
        return static::find()
            ->where(['user_login' => $user_login])
            //->andWhere(['user_role' => 'administrator'])
            ->andWhere(['or', ['user_role' => 'administrator'], ['user_role' => 'agent']])
            ->one();
        //return static::findOne(['user_login' => $user_login])
            
        ;
    }

    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
//Yii::info("validateAuthKey", 'apiResponse');
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($user_pass)
    {
        return $this->user_pass === sha1(mb_strtoupper($this->user_login) . ":" . $user_pass);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($user_pass)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($user_pass);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
    /** EXTENSION MOVIE **/

//    protected function loginByCookie()
//    {
//        parent::loginByCookie();
//	if ($this->getIsGuest()) {
//            $value = Yii::$app->getRequest()->getPosts()->getValue($this->identityCookie['name']);
//        }
//	return;
//        $value = Yii::$app->getRequest()->getCookies()->getValue($this->identityCookie['name']);
//        if ($value === null) {
//            return;
//        }
//
//        $data = json_decode($value, true);
//        if (count($data) !== 3 || !isset($data[0], $data[1], $data[2])) {
//            return;
//        }
//
//        list ($id, $authKey, $duration) = $data;
//        /* @var $class IdentityInterface */
//        $class = $this->identityClass;
//        $identity = $class::findIdentity($id);
//        if ($identity === null) {
//            return;
//        } elseif (!$identity instanceof IdentityInterface) {
//            throw new InvalidValueException("$class::findIdentity() must return an object implementing IdentityInterface.");
//        }
//
//        if ($identity->validateAuthKey($authKey)) {
//            if ($this->beforeLogin($identity, true, $duration)) {
//                $this->switchIdentity($identity, $this->autoRenewCookie ? $duration : 0);
//                $ip = Yii::$app->getRequest()->getUserIP();
//                Yii::info("User '$id' logged in from $ip via cookie.", __METHOD__);
//                $this->afterLogin($identity, true, $duration);
//            }
//        } else {
//            Yii::warning("Invalid auth key attempted for user '$id': $authKey", __METHOD__);
//        }
//    }

    

    public function getStatus($state)
    {
        $statuses = array(
            'Training' => 'Training',
            'Lunch' => 'Lunch',
            'O/B' => 'O/B',
            'Online' => 'Online',
        );

        return $statuses[$state];
    }

    
    

    public function beforeSave($insert) {

        if (parent::beforeSave($insert)) {

            if ($insert || $this->getOldAttribute("user_pass") != $this->user_pass) {
                $this->user_pass = sha1(mb_strtoupper($this->user_login) . ":" . $this->user_pass); 
            }
            //if ($this->isNewRecord) {
                //$this->auth_key = \Yii::$app->security->generateRandomString();
            //}

            return true;
        } else {
            return false;
        }
      
        //return parent::beforeSave($insert);
    }

   

}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use app\models\UsersSearch;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;



/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => ['class' => 'app\components\AccessRule'],
                'rules' => [
                    [   
                        'actions' => ['index','clients', 'create', 'update','delete'],
                        'allow' => true,
                        'roles' => ['administrator'],
                    ],
                    [   
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [   
                        'actions' => ['login'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    { 
        $searchModel = new UsersSearch();
        $filter = ['role' => 'agent'];
        $params = array_merge($filter, Yii::$app->request->queryParams);
        $dataProvider = $searchModel->search($params);
      
        return $this->render('index',[
           'searchModel' => $searchModel,
           'dataProvider' => $dataProvider,
        ]);
    }

    public function actionClients()
    {
        $searchModel = new UsersSearch();
        $filter = ['role' => 'customer'];
        $params = array_merge($filter, Yii::$app->request->queryParams);
        $dataProvider = $searchModel->search($params);
       
        return $this->render('clients',[
           'searchModel' => $searchModel,
           'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model. To create operator, agent, client
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();
        $model->scenario = Users::SCENARIO_CREATE_ANY_USER;        
        $post = Yii::$app->request->post();  
        $type = Yii::$app->request->get('type'); 
        $type = ($type == 'agent') ? 'agent' : 'customer';     

        if ($post) {
             $post['Users']['user_role'] = $type;           
            // echo $model->scenario;die;
            /*if ($post['Users']['create_at'] !== '') {
                $post['Users']['create_at'] = str_replace('/', '-', $post['Users']['create_at']);
                $post['Users']['create_at'] = date('Y-m-d H:i:s', strtotime($post['Users']['create_at'])); 
            }  */            
        } 
        if ($model->load($post) && $model->save() ) {  
            $action = ($type == 'agent') ? 'index' : 'clients';             
            return $this->redirect(['users/' . $action]);             
        } else {          
            return $this->render('create', [
                'model' => $model,
                
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {  
        $model = $this->findModel($id);      
        $model->scenario = Users::SCENARIO_USER_UPDATE;
        $post = Yii::$app->request->post(); 

        if ($post) {
            if (trim($post['Users']['user_pass']) == '') {
                unset($post['Users']['user_pass']);
            } 
        } 
        /*if ($post && $post['Users']['user_create'] !== '') {         
            $post['Users']['user_create'] = str_replace('/', '-', $post['Users']['user_create']);
            $post['Users']['user_create'] = date('Y-m-d H:i:s', strtotime($post['Users']['user_create']));
                        
        }*/

        if ($model->load($post) && $model->save()) {
            //echo $model->scenario;die;
            $action = ($model->user_role == 'agent') ? 'index' : 'clients';           
            return $this->redirect(['users/' . $action]);
        } else {
            unset($model->user_pass);
            $model->user_create = date('d/m/Y', strtotime($model->user_create));
            return $this->render('update', [
                'model' => $model,                
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);
        $action = ($user->user_role == 'agent') ? 'index' : 'clients';
        $user->delete();

        return $this->redirect([$action]);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    

    

    
}

views/users/_form.php
<?php

use yii\helpers\Html;
//use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveForm;
use dosamigos\datepicker\DatePicker;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */


  $this->title = 'Add user';

if ($model->id) {
    $this->title .= ' ' . $model->user_nick;
} 
?>
<div class="site-index">
 <div class="jumbotron">
    <h3><?php echo Html::encode($this->title) ?></h3>
    <br><br>

    <div class="users-form">

        <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

        <div class="row">
          <div class="col-md-6">
         
          <?php echo $form->field($model, 'user_nick',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->textInput(['maxlength' => true]) ?>

             <?php /*echo $form->field($model, 'user_role',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->dropDownList([ 'agent' => 'Agent', 'customer' => 'Client' ], ['prompt' => '']) */ ?>
        
          
         
          
         
          <?php /*echo $form->field($model, 'user_create')->widget(
                            DatePicker::className(), [                               
                                'language' => 'ru',
                                 'attribute' => 'date',
                                'template' => '{addon}{input}',
                                    'clientOptions' => [
                                        'autoclose' => true,
                                        'format' => 'dd/m/yyyy'
                                    ]
                        ]); */ ?>
       
          </div>
          <div class="col-md-6">
             
              <?php echo $form->field($model, 'user_state',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->dropDownList([ 'Training' => 'Training', 'Lunch' => 'Lunch', 'O/B' => 'O/B', 'Online' => 'Online' ], []) ?>

          </div>
          <div class="col-md-6">
             
              <?php echo $form->field($model, 'user_capacity',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->textInput(['maxlength' => true]) ?>

          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
              <?php echo $form->field($model, 'user_login',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->textInput(['maxlength' => true, 'disabled' => !$model->isNewRecord]) ?>
              <?php echo $form->field($model, 'user_pass',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->passwordInput(['maxlength' => true]) ?>
              <?php echo $form->field($model, 'confirm_password',[
                'horizontalCssClasses' => [
                    'wrapper' => 'col-sm-6',
                ]
            ])->passwordInput() ?>
            </div>
             

         

            <div class="row">
                <div class="col-md-6">
       
                </div>
                <div class="col-md-6">
                     <br><br>
                     <div class="form-group">
                        <?php echo Html::submitButton('Save', [
                            'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary', 
                            'style' => 'font-size: 14px;'] ) ?>
                    </div>
                </div>
            </div> 
         
        <?php ActiveForm::end(); ?>

    </div>
    </div>
  </div>
</div>

views/users/clients.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;
use yii\helpers\Url;
/* @var $this yii\web\View */

$type = trim(Yii::$app->request->get('type'));  
$this->title = 'Agents';
?>
<div class="site-index">
    <div class="jumbotron">
        <h2>Clients</h2>

        <p class="text-right">            
            <a href="<?php echo Url::toRoute(['users/create', 'type' => 'client' ]) ?>">Add client</a>
        </p>

        <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        'layout'=>"{items}\n{pager}",
        
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute'=>'user_id',
                'label'=>'№ ID',                
            ], 
            [
                'attribute'=>'user_nick',
                'label'=>'Nick name',                
            ],
            [
                'attribute'=>'user_login',
                'label'=>'Login',                
            ],
            [
	            'attribute' => 'user_create',
		    	'label' => 'Created at',
		    	'format' => ['date', 'php:d.m.Y']
            ],            
            [
	           	'attribute'=>'user_state',
		    	'label'=>'State',
		    	'format' => 'text',
		    	'content' => function($data) {
					return $data->getStatus($data->user_state);
		    	},
           ],           
           [
            'class' => 'yii\grid\ActionColumn',
            'header'=>'Actions', 
            'headerOptions' => ['width' => '80'],
            'template' => '{update} {delete}{link}',
            
            ],
        ],
    ]); ?>


    </div>
</div>

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */


/*$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;*/
?>
<div class="users-create">   

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;
use yii\helpers\Url;
/* @var $this yii\web\View */

$type = trim(Yii::$app->request->get('type'));  
$this->title = 'Agents';
?>
<div class="site-index">
    <div class="jumbotron">
        <h2>Agents</h2>

        <p class="text-right">            
            <a href="<?php echo Url::toRoute(['users/create', 'type' => 'agent']) ?>">Add agent</a>
        </p>

        <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        'layout'=>"{items}\n{pager}",
        
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute'=>'user_id',
                'label'=>'№ ID',                
            ], 
            [
                'attribute'=>'user_nick',
                'label'=>'Nick name',                
            ],
            [
                'attribute'=>'user_login',
                'label'=>'Login',                
            ],
            [
                'attribute'=>'user_capacity',
                'label'=>'Capacity',                
            ],
            [
	            'attribute' => 'user_create',
		    	'label' => 'Created at',
		    	'format' => ['date', 'php:d.m.Y']
            ],            
            [
	           	'attribute'=>'user_state',
		    	'label'=>'State',
		    	'format' => 'text',
		    	'content' => function($data) {
					return $data->getStatus($data->user_state);
		    	},
           ],           
           [
            'class' => 'yii\grid\ActionColumn',
            'header'=>'Actions', 
            'headerOptions' => ['width' => '80'],
            'template' => '{update} {delete}{link}',
            ],
        ],
    ]); ?>


    </div>
</div>

views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */



//$this->title = 'Update Users: ' . ' ' . $model->id;
/*$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';*/
?>
<div class="users-update">    

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>